#!/bin/bash
#
# Use this script to copy one or more changed files into
# multiple branches
#
git checkout $1 && \
git checkout VLAN_PreDeploy_Check -- README.md && \
git status && \
git commit -m 'Update test description in README.md'
